/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication59;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
/**
 *
 * @author Luis
 */
public class AhorcadoJuego extends JFrame {
private JLabel labelDibujo;
    private JButton buttonAdivinar;
    private JMenu menu;
    private JMenuBar menuBar;
    private JMenuItem menuItemNuevoJuego;
    /**
     * Creates new form AhorcadoJuego
     */
     public AhorcadoJuego() {
        // Configurar JFrame
        setTitle("Juego del Ahorcado");
        setSize(400, 400);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        // Configurar dibujo
        labelDibujo = new JLabel();
        labelDibujo.setHorizontalAlignment(JLabel.CENTER);
        labelDibujo.setVerticalAlignment(JLabel.CENTER);
        add(labelDibujo, BorderLayout.CENTER);

        // Configurar botón de adivinar
        buttonAdivinar = new JButton("Adivinar");
        buttonAdivinar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Lógica para adivinar una letra
                // Actualizar dibujo según se adivine o no
            }
        });
        add(buttonAdivinar, BorderLayout.SOUTH);

        // Configurar menú
        menu = new JMenu("Juego");
        menuItemNuevoJuego = new JMenuItem("Nuevo Juego");
        menuItemNuevoJuego.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Lógica para comenzar un nuevo juego
                // Reiniciar dibujo y otros elementos del juego
            }
        });
        menu.add(menuItemNuevoJuego);
        menuBar = new JMenuBar();
        menuBar.add(menu);
        setJMenuBar(menuBar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        AhorcadoJuego juego = new AhorcadoJuego();
        juego.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
